### ISSUE TITLE
How to run the code in Desktop

### ISSUE THREAD

**Issue by VincentOracle** [opchaves/gochaves#1]
How do we  run the code in Desktop. What are the dependencies need

**Comment by opchaves** [comment]
> How do we  run the code in Desktop. What are the dependencies need

You need to have "bun" and "hugo"

The website folder is static website created with hugo. You may add new pages under website/content and then use the hugo cli to compile the .md files to .html.  The generated html files are placed under "website/public". 

The webserver is a bun+hono application. Hono serves the static website generated by hugo. Data is stored in sqlite using drizzle and bun:sqlite. Before you run the server you need to rum the  "migrate" command and the you start the app with "nom run dev"

**Comment by VincentOracle** [comment]
Thankyou so much,,it has worked for me
